### ISSUE TITLE
Users can ask for some suggestions in a separate chat screen from AI

### ISSUE THREAD

**Issue by VishwaiOSDev** [kantzz-GitHub/TasteCraft-iOS#4]
As a user, I want an **quick recipe or recommendation** that I can make using the **things I have on hand**.

**Comment by kantzz-GitHub** [comment]
This issue was canceled for the reason being too technically challenging and thus requiring a significant amount of time. 
There is a chance it could still be implemented in case we have a lot of free time left after completion of Sprint 4
